-- Adiciona tabela de Comentários e Insights do mês, por cliente.
-- Rodar no SQL Editor do mesmo projeto Supabase (rpibvjcnrseuugpkfmdj).

create table public.rel_comentarios_mensais (
  id bigint generated by default as identity primary key,
  cliente_id bigint not null references public.rel_clientes(id) on delete cascade,
  mes_referencia date not null,
  texto text not null default '',
  atualizado_em timestamptz default now(),
  unique (cliente_id, mes_referencia)
);
alter table public.rel_comentarios_mensais enable row level security;
create policy "anon full access" on public.rel_comentarios_mensais for all to anon using (true) with check (true);
alter publication supabase_realtime add table public.rel_comentarios_mensais;

comment on table public.rel_comentarios_mensais is
  'Comentários/insights de texto livre por cliente e mês, editados na Visão Geral e incluídos no relatório exportado.';

NOTIFY pgrst, 'reload schema';
