-- LAWgico Relatório — piloto multi-cliente
-- Rodar no SQL Editor do projeto Supabase rpibvjcnrseuugpkfmdj (mesmo dos
-- outros tools LAWgico). Substitui o schema fixo (bs_contingencia_snapshot/
-- bs_pagamentos, específico da Bridgestone) por um schema genérico que
-- serve qualquer cliente do escritório sem precisar alterar o banco a cada
-- cliente novo. As tabelas antigas NÃO são apagadas por este script — a
-- migração (migrar_bridgestone.py) lê delas e grava aqui; elas só devem
-- ser descontinuadas depois de confirmar que a migração bateu.

create table public.rel_clientes (
  id bigint generated by default as identity primary key,
  nome text not null,
  slug text not null unique,
  ativo boolean not null default true,
  criado_em timestamptz default now()
);
alter table public.rel_clientes enable row level security;
create policy "anon full access" on public.rel_clientes for all to anon using (true) with check (true);
alter publication supabase_realtime add table public.rel_clientes;

comment on table public.rel_clientes is
  'Um registro por cliente do escritório atendido pela ferramenta (piloto multi-cliente do LAWgico Relatório).';

create table public.rel_config_cliente (
  id bigint generated by default as identity primary key,
  cliente_id bigint not null references public.rel_clientes(id) on delete cascade,
  config jsonb not null,
  criado_em timestamptz default now()
);
alter table public.rel_config_cliente enable row level security;
create policy "anon full access" on public.rel_config_cliente for all to anon using (true) with check (true);
alter publication supabase_realtime add table public.rel_config_cliente;

comment on table public.rel_config_cliente is
  'Config "modelo" de cada cliente: colunas do relatório de processos (nome de exibição + nome da coluna de origem no export do eLaw), colunas do relatório de pagamentos, e como detectar processo encerrado. Formato do jsonb em config:
  {
    "colunas_processos": [{"origem":"Process","label":"Processo","chave":true}, {"origem":"Plaintiff","label":"Reclamante"}, ...],
    "colunas_pagamentos": [{"origem":"Processo","label":"Processo","chave":true}, ...],
    "encerrado": {"fonte":"comparacao_mes_anterior"} ou {"fonte":"campo_status","campo":"Status","valores_encerrado":["Closed","Encerrado"]},
    "campo_base_correcao": "Accrual"  -- opcional, usado quando o upload usa origem "manual" do índice
  }
  Sempre usa a config mais recente (maior id) do cliente — não versiona por enquanto.';

create table public.rel_processos_snapshot (
  id bigint generated by default as identity primary key,
  cliente_id bigint not null references public.rel_clientes(id) on delete cascade,
  mes_referencia date not null,
  processo text not null,
  dados jsonb not null default '{}'::jsonb,
  status_calculado text,             -- 'novo' | 'ativo' | 'encerrado'
  criado_em timestamptz default now(),
  unique (cliente_id, mes_referencia, processo)
);
alter table public.rel_processos_snapshot enable row level security;
create policy "anon full access" on public.rel_processos_snapshot for all to anon using (true) with check (true);
alter publication supabase_realtime add table public.rel_processos_snapshot;
create index rel_processos_snapshot_cliente_mes on public.rel_processos_snapshot (cliente_id, mes_referencia);

comment on table public.rel_processos_snapshot is
  'Um snapshot por processo por mês por cliente. dados jsonb guarda todos os campos variáveis do modelo daquele cliente (ver rel_config_cliente.colunas_processos) — coluna fixa só pra chaves de junção/filtro (cliente, mês, processo) e pro status calculado de novo/ativo/encerrado.';

create table public.rel_pagamentos_snapshot (
  id bigint generated by default as identity primary key,
  cliente_id bigint not null references public.rel_clientes(id) on delete cascade,
  mes_referencia date not null,
  processo text not null,
  dados jsonb not null default '{}'::jsonb,
  criado_em timestamptz default now(),
  unique (cliente_id, mes_referencia, processo)
);
alter table public.rel_pagamentos_snapshot enable row level security;
create policy "anon full access" on public.rel_pagamentos_snapshot for all to anon using (true) with check (true);
alter publication supabase_realtime add table public.rel_pagamentos_snapshot;
create index rel_pagamentos_snapshot_cliente_mes on public.rel_pagamentos_snapshot (cliente_id, mes_referencia);

comment on table public.rel_pagamentos_snapshot is
  'Ledger de pagamentos/garantias por processo por mês por cliente, mesmo padrão de dados jsonb de rel_processos_snapshot. Junta com rel_processos_snapshot por (cliente_id, mes_referencia, processo).';

create table public.rel_indices_mensais (
  id bigint generated by default as identity primary key,
  cliente_id bigint not null references public.rel_clientes(id) on delete cascade,
  mes_referencia date not null,
  tipo_indice text not null,         -- 'IPCA' | 'SELIC' | 'TR' | outro
  valor numeric not null,            -- percentual do período, ex: 0.42 = 0,42%
  origem_aplicada text not null default 'elaw',  -- 'elaw' (só registro) | 'manual' (foi de fato aplicado na correção)
  criado_em timestamptz default now()
);
alter table public.rel_indices_mensais enable row level security;
create policy "anon full access" on public.rel_indices_mensais for all to anon using (true) with check (true);
alter publication supabase_realtime add table public.rel_indices_mensais;

comment on table public.rel_indices_mensais is
  'Índice(s) de atualização (IPCA/SELIC/TR) informado(s) a cada upload mensal por cliente. origem_aplicada registra se o índice só foi anotado (eLaw já trouxe o valor calculado) ou se foi de fato usado pra corrigir valores nesse upload (manual = valor_corrigido = valor_base × (1 + valor/100), correção simples de um período).';

NOTIFY pgrst, 'reload schema';
